
name: DhonduMaharaj
on:
  push:
    branches:
      - 'main'
jobs:
  DhonduMaharaj:
    runs-on: ASUS
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
